server:
    port: 8086
    compression:
        enabled: true
        excluded-user-agents: 
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/n-triples,application/turtle,text/turtle,application/x-turtle,application/rdf+xml,application/rdf+json
        min-response-size: 1
#    context-path: /
#

spring: 
    main:
        banner-mode: "off"     

logging: 
    level: 
        org: 
            springframework: DEBUG

